# vim ft=yaml
# travis-ci.org definition for python-patterns build
language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# Disabled for now since cause more pain than gain
#  - "pypy"
#  - "pypy3"

cache:
  - pip

install:
  - travis_retry pip install -q codecov
  - pip install flake8
  - pip install -r requirements-dev.txt

script:
  - pytest --doctest-modules behavioral/ creational/ dft/ fundamental/ other/ structural/  # exclude tests/
  - pytest -s -vv --cov=. --log-level=INFO tests/
  # Actually run all the scripts, contributing to coverage
  - PYTHONPATH=. ./run_all.sh
  - flake8 *py

after_success:
  - codecov
