# vim ft=yaml
# travis-ci.org definition for python-patterns build
language: python

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  - pip

install:
  - pip install -r requirements-dev.txt

script:
  - pytest --doctest-modules patterns/
  - pytest -s -vv --cov=. --log-level=INFO tests/
  # Actually run all the scripts, contributing to coverage
  - PYTHONPATH=. ./run_all.sh
  - flake8 *py

after_success:
  - codecov
