# vim ft=yaml
# travis-ci.org definition for python-patterns build
language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

cache:
  - pip

install:
  - travis_retry pip install -q coveralls codecov
  - pip install flake8  # eventually worth

script:
  # Run tests
  - PYTHONPATH=. nosetests -s -v --with-doctest --with-cov --cover-package . --logging-level=INFO -v .
  # Actually run all the scripts, contributing to coverage
  - bash -c 'failed=""; for f in [^_]*py; do python `which coverage` run -a $f || failed+=" $f"; echo "I: done $f. Exit code $?"; done; [ -z "$failed" ] || { echo "Failed: $failed"; exit 1; }'
  # for now failure in flaking is ignored
  - flake8 *py || echo "PEP8 the code"

after_success:
  - coveralls
  - codecov
