os: linux
dist: focal
language: python

jobs:
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.9"
      env: TOXENV=py39

cache:
  - pip

install:
  - pip install codecov tox

script:
  - tox

after_success:
  - codecov
